//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizSparkSupport.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public long CodeID { get; set; }
        public string CodeValue { get; set; }
        public bool UsedBefore { get; set; }
        public System.DateTime ExpireAt { get; set; }
        public Nullable<bool> Sent { get; set; }
    }
}
