//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizSparkSupport.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Case
    {
        public long CaseID { get; set; }
        public long EmployeeID { get; set; }
        public Nullable<System.DateTime> OpenedAt { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
