//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizSparkSupport.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public long FileID { get; set; }
        public byte[] Content { get; set; }
        public long CaseID { get; set; }
        public string FileName { get; set; }
        public string SavedFileName { get; set; }
        public string FileType { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
