//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizSparkSupport.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.Employee_Case = new HashSet<Employee_Case>();
            this.Files = new HashSet<File>();
            this.Messages = new HashSet<Message>();
        }
    
        public long CaseID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
        public int CategoryID { get; set; }
        public long StartupID { get; set; }
        public int PriorityID { get; set; }
        public int StatusID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Startup Startup { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Case> Employee_Case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
    }
}
