//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizSparkSupport.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageID { get; set; }
        public long SenderID { get; set; }
        public long ReceiverID { get; set; }
        public string MessageContent { get; set; }
        public long CaseID { get; set; }
        public System.DateTime SubmissionDate { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
